apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ace-pipeline-demo
  namespace: cp4i
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-KSBM-CCBJUS
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: 'image-registry.openshift-image-registry.svc:5000/cp4i/ace-image:latest'
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  adminServerSecure: true
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  version: '12.0.3.0-r2'
  replicas: 1
  configurations: []