apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-pipeline
  namespace: cp4i
spec:
  params:
    - default: 'image-registry.openshift-image-registry.svc:5000/cp4i/ace-image:latest'
      name: IMAGE_NAME
      type: string
    - default: 'https://github.com/MGsus/ace-pipeline-demo'
      name: GIT_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: FORMAT
          value: docker
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy-integration-server
      params:
        - name: SCRIPT
          value: |
            oc apply -f ./integration-server.yaml
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
  workspaces:
    - name: workspace
